### ISSUE TITLE
Player Component: Inventory

### ISSUE THREAD

**Issue by starim** [devinleonhart/wordsmith#38]
"Inventory" of Player Words and Item Words. Which, if clicked, increment the "Word Count". Clicking the same word again decrements the word count. The purpose of the word count is to show the GM, at a glance, what the player is using in their post for the awarding of Player Dice. The UI should show the buttons as depressed or highlighted, to tell the GM exactly which words were used.

Subtask of issue #13

![playercomponent](https://cloud.githubusercontent.com/assets/2824816/14067010/1faa398a-f40f-11e5-8e3a-caf2f8ba3b77.png)

**Comment by starim** [comment]
@devinleonhart The picture doesn't illustrate the word counter, which sounds like a GM-only feature. Could you get a screenshot from current Wordsmith showing the word counter?

**Comment by devinleonhart** [comment]
@starim My apologies. The SS doesn't show my goal with this feature.

The objective was to visually demonstrate to the player their contribution to the post in a mechanical way instead of just expressing it in their post. 

For example, players tend to fall into this behavior : 

"Using my super **strength**, I will lift the gate."

This is limiting the ability for the player to express themselves, because they think they have to keep saying their related words to their action to make sure they are used. 

When a word is selected, it should provide some feedback that that particular word is being used, thus the depression of the button. For the word count, it's just a total of how many buttons were pressed. It represents the number of player dice that are being added. 

And another thing to note, this does not actually increase the roll. It's just a suggestion to the DM of what the player thinks they deserve based on what they typed. So it needs to be a visual indicator and nothing else.

**Comment by starim** [comment]
Added a `selected` property to player words in Firebase to support the word count feature.
